#!/usr/bin/env python3
"""
Documentation Generator Server
Phase 7: Auto documentation generation
"""

import re
import os
import ollama
from typing import Dict, List, Optional


class DocsGeneratorServer:
    """Generate documentation for embedded firmware projects."""

    def __init__(self, host: str = None, model: str = None):
        self.host = host or os.getenv("OLLAMA_HOST", "http://localhost:11434")
        self.model = model or os.getenv("OLLAMA_MODEL", "llama3")
        self.client = ollama.Client(host=self.host)

    # =====================================================================
    # QUALITY REPORT (UPDATED)
    # =====================================================================

    def generate_quality_report(self, quality_result: Dict) -> str:
        """Generate code quality report section for documentation."""

        # Safe memory formatting
        memory = quality_result.get("estimated_ram_usage_percent")
        memory_str = f"{memory:.1f}%" if isinstance(memory, (int, float)) else "N/A"

        report = f"""## Code Quality Report

**Overall Score:** {quality_result.get('quality_score', 'N/A')}/100  
**Severity Level:** {quality_result.get('severity', 'unknown').upper()}  
**Memory Usage:** {memory_str}

### Summary
{quality_result.get('summary', 'No summary available')}

"""

        # -------------------------------
        # Robust severity handling
        # -------------------------------
        issues_by_severity = quality_result.get("issues_by_severity")

        # Backward compatibility fallback
        if not issues_by_severity:
            issues_by_severity = {}
            for issue in quality_result.get("issues", []):
                sev = issue.get("severity", "medium")
                issues_by_severity.setdefault(sev, []).append(issue)

        severity_order = ["critical", "high", "medium", "low"]
        icons = {
            "critical": "🚨",
            "high": "⚠️",
            "medium": "ℹ️",
            "low": "💡"
        }

        for severity in severity_order:
            issues = issues_by_severity.get(severity, [])
            if issues:
                report += f"\n### {icons[severity]} {severity.upper()} Issues ({len(issues)})\n\n"

                for issue in issues[:5]:
                    issue_type = issue.get("type", "General").title()
                    message = issue.get("message", "No details provided")
                    suggestion = issue.get("suggestion", "No automatic fix suggested.")

                    report += f"**{issue_type}:** {message}  \n"
                    report += f"*Fix:* {suggestion}\n\n"

        report += "\n---\n"
        return report

    # =====================================================================
    # EXISTING DOCUMENTATION LOGIC (UNCHANGED)
    # =====================================================================

    def generate_full_documentation(
        self,
        code: str,
        description: str,
        libraries: Optional[List[str]] = None,
        quality_result: Optional[Dict] = None
    ) -> str:
        """Generate full project documentation."""

        doc = f"# {description}\n\n"

        doc += "## Overview\n"
        doc += f"{description}\n\n"

        if libraries:
            doc += "## Libraries Used\n"
            for lib in libraries:
                doc += f"- {lib}\n"
            doc += "\n"

        if quality_result:
            doc += self.generate_quality_report(quality_result)

        doc += "## Notes\n"
        doc += "This documentation was auto-generated by the MCP Documentation Generator.\n"

        return doc


# =====================================================================
# TEST MODE
# =====================================================================

if __name__ == "__main__":
    print("\n" + "=" * 70)
    print("Docs Generator Server - Test Mode")
    print("=" * 70 + "\n")

    server = DocsGeneratorServer()

    sample_quality = {
        "quality_score": 78,
        "severity": "medium",
        "estimated_ram_usage_percent": 56.2,
        "summary": "Code is functional but has some performance issues.",
        "issues": [
            {
                "type": "performance",
                "severity": "medium",
                "message": "Blocking delay() detected",
                "suggestion": "Use millis()-based non-blocking timing"
            }
        ]
    }

    print(server.generate_quality_report(sample_quality))
